### ISSUE TITLE
It's showing a TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by ukicomputers** [WebDevSimplified/Node.js-Stripe-Shopping-Cart#4]
I'am all coded from video will you showed, and after all coding, this error showes me after purcaching a item:

D:\Libaries\Desktop\Node.js\shop\server.js:40
      req.body.items.forEach(function(item) {
                     ^

TypeError: Cannot read property 'forEach' of undefined
    at D:\Libaries\Desktop\Node.js\shop\server.js:40:22
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)

Please help me. Thanks advance, @WebDevSimplified .

**Comment by ukicomputers** [comment]
Nothing. I'am resloved a problem.

**Comment by alex0754** [comment]
Hey, how did you solve it?
